# Generated by Django 5.0.3 on 2024-05-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
    ]
