# Generated by Django 5.0.3 on 2024-05-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
    ]
