# Generated by Django 5.0.3 on 2024-05-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutdetals',
            name='date_of_birth',
        ),
    ]
