# Generated by Django 5.0.3 on 2024-05-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_layoutdetals_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
    ]
