# Generated by Django 5.0.3 on 2024-05-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutdetals',
            name='date_of_birth',
        ),
    ]
