# Generated by Django 5.0.3 on 2024-05-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
    ]
