# Generated by Django 5.0.3 on 2024-05-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledetails',
            name='layout',
        ),
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
        migrations.DeleteModel(
            name='TableDetails',
        ),
    ]
