# Generated by Django 5.0.3 on 2024-05-05 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledetails',
            name='dateofentry',
        ),
        migrations.AddField(
            model_name='tabledetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
