# Generated by Django 5.0.3 on 2024-05-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_tabledetails_dateofentry_tabledetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledetails',
            name='layout',
        ),
        migrations.DeleteModel(
            name='LayoutDetals',
        ),
        migrations.DeleteModel(
            name='TableDetails',
        ),
    ]
